import uuid
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class WorkflowNodeRequest(BaseModel):
    client_id: str = Field(
        ...,
        description="Temporary unique ID generated by the FE (e.g., 'node_1') to map dependencies.",
    )
    type: Literal["send_email", "generate_report", "upload_file"] = Field(
        ..., description="Job handler type"
    )
    payload: dict[str, Any] = Field(default_factory=dict, description="JSON payload for the job")
    priority: Literal[1, 2, 3] = Field(2, description="1 (High), 2 (Medium), 3 (Low)")
    dependencies: list[str] = Field(
        default_factory=list, description="List of client_ids this node depends on."
    )


class CreateWorkflowRequest(BaseModel):
    name: str | None = Field(None, description="Optional name for the workflow")
    scheduled_at: datetime | None = Field(
        None, description="Run at specific future time (ISO format)"
    )
    recurring_interval: Literal["every_1_minute", "every_5_minutes", "every_1_hour"] | None = Field(
        None,
        description="Optional recurring schedule",
    )
    nodes: list[WorkflowNodeRequest] = Field(..., description="List of nodes in the DAG workflow")


class WorkflowNodeResponse(BaseModel):
    id: uuid.UUID
    client_id: str
    type: str
    payload: dict[str, Any]
    priority: int
    dependencies: list[str] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)


class WorkflowResponse(BaseModel):
    id: uuid.UUID
    name: str | None
    scheduled_at: datetime | None
    recurring_interval: str | None
    created_at: datetime
    updated_at: datetime
    nodes: list[WorkflowNodeResponse] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)
