"""add sent_emails table

Revision ID: 5103711e4a61
Revises: 8600b54ab753
Create Date: 2026-06-10 16:34:37.636910

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5103711e4a61"
down_revision: str | Sequence[str] | None = "8600b54ab753"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sent_emails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sent_emails_job_id"), "sent_emails", ["job_id"], unique=False)
    op.create_index(op.f("ix_sent_emails_sent_at"), "sent_emails", ["sent_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sent_emails_sent_at"), table_name="sent_emails")
    op.drop_index(op.f("ix_sent_emails_job_id"), table_name="sent_emails")
    op.drop_table("sent_emails")
    # ### end Alembic commands ###
