"""Add workflow tables

Revision ID: 65af8b323e4a
Revises: 5103711e4a61
Create Date: 2026-06-11 19:29:06.949710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "65af8b323e4a"
down_revision: str | Sequence[str] | None = "5103711e4a61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recurring_interval", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflows_scheduled_at"), "workflows", ["scheduled_at"], unique=False)
    op.create_table(
        "workflow_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_nodes_workflow_id"), "workflow_nodes", ["workflow_id"], unique=False
    )
    op.create_table(
        "workflow_node_dependencies",
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_node_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["depends_on_node_id"], ["workflow_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["workflow_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("node_id", "depends_on_node_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_node_dependencies")
    op.drop_index(op.f("ix_workflow_nodes_workflow_id"), table_name="workflow_nodes")
    op.drop_table("workflow_nodes")
    op.drop_index(op.f("ix_workflows_scheduled_at"), table_name="workflows")
    op.drop_table("workflows")
    # ### end Alembic commands ###
